baseurl: /
languageCode: en-us
title: A Data Blog
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
enableEmoji: true
disable_codefolding: false
# Set to "hide" or "show" all codes by default
codefolding_show: show
codefolding_nobutton: true
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Blog
      url: /post/
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/dsobolew
      weight: 4
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang: ["r","yaml"]
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: wint.jpg
    width: 50
    